<?php
// coolify-mirror helper. Executed inside the "coolify" container as www-data:
//   docker exec -i -u www-data -e CM_ACTION=... -e CM_INPUT=<base64 json> coolify php < runner.php
// It only calls Coolify's own actions so that containers, labels and proxy
// configuration are generated by Coolify itself.
error_reporting(E_ALL & ~E_DEPRECATED & ~E_USER_DEPRECATED);
ini_set('display_errors', 'stderr');
chdir('/var/www/html');
require '/var/www/html/vendor/autoload.php';
$app = require '/var/www/html/bootstrap/app.php';
$app->make(Illuminate\Contracts\Console\Kernel::class)->bootstrap();

use App\Models\Application;
use App\Models\ApplicationDeploymentQueue;
use App\Models\Server;
use App\Models\Service;
use Illuminate\Support\Facades\Crypt;

function cm_out(array $result): void
{
    echo "\n@@CM_RESULT@@".json_encode($result, JSON_UNESCAPED_SLASHES | JSON_PARTIAL_OUTPUT_ON_ERROR)."\n";
}

function cm_database_models(): array
{
    return [
        'standalone_postgresqls' => App\Models\StandalonePostgresql::class,
        'standalone_redis' => App\Models\StandaloneRedis::class,
        'standalone_mongodbs' => App\Models\StandaloneMongodb::class,
        'standalone_mysqls' => App\Models\StandaloneMysql::class,
        'standalone_mariadbs' => App\Models\StandaloneMariadb::class,
        'standalone_keydbs' => App\Models\StandaloneKeydb::class,
        'standalone_dragonflies' => App\Models\StandaloneDragonfly::class,
        'standalone_clickhouses' => App\Models\StandaloneClickhouse::class,
    ];
}

$action = getenv('CM_ACTION') ?: '';
$input = json_decode(base64_decode(getenv('CM_INPUT') ?: 'bnVsbA=='), true);
$result = ['ok' => true];

try {
    switch ($action) {
        case 'version':
            $result['version'] = (string) config('constants.coolify.version');
            break;

        case 'capabilities':
            // Everything of Coolify this helper relies on, per feature: a
            // Coolify update that renames or removes something is reported
            // precisely instead of failing in the middle of a restore.
            $has = function (array $need): array {
                $missing = [];
                foreach ($need as $item) {
                    if (str_contains($item, '::')) {
                        [$class, $method] = explode('::', $item, 2);
                        if (! class_exists($class) || ! method_exists($class, $method)) {
                            $missing[] = $item;
                        }
                    } elseif (str_ends_with($item, '()')) {
                        if (! function_exists(substr($item, 0, -2))) {
                            $missing[] = $item;
                        }
                    } elseif (! class_exists($item)) {
                        $missing[] = $item;
                    }
                }

                return $missing;
            };
            $features = [
                'core' => array_merge([
                    'App\Models\Application', 'App\Models\ApplicationDeploymentQueue', 'App\Models\Server',
                    'App\Models\Service', 'App\Models\Project', 'App\Models\Environment',
                    'App\Models\Server::isFunctional', 'App\Models\Server::proxyType',
                    'App\Actions\Server\ValidateServer::run', 'App\Actions\Proxy\CheckProxy::run', 'App\Actions\Proxy\StartProxy::run',
                    'App\Actions\Service\StartService::run', 'App\Actions\Database\StartDatabase::dispatch',
                    'queue_application_deployment()', 'new_public_id()', 'data_get()',
                ], array_values(cm_database_models())),
                'no_rebuild' => ['App\Models\Application::markDeploymentConfigurationApplied'],
                'compose_start' => [
                    'App\Models\Application::parse', 'App\Models\Application::workdir', 'App\Models\Application::link',
                    'App\Jobs\ApplicationDeploymentJob::generate_runtime_environment_variables',
                    'App\Jobs\ApplicationDeploymentJob::resolveContainerName',
                    'App\Models\ApplicationDeploymentQueue::addLogEntry', 'convertToArray()',
                ],
                'domains' => ['App\Models\ServiceApplication', 'App\Models\Service::parse', 'updateCompose()', 'generateLabelsApplication()'],
                'transfer_bundle' => [
                    'App\Services\ServerTransfer\ServerTransferBundle::wrap', 'App\Services\ServerTransfer\ServerTransferBundle::validate',
                    'App\Services\ServerTransfer\ServerTransferExporter::collectProjectIds',
                    'App\Services\ServerTransfer\ServerTransferExporter::destinationUuidMap',
                    'App\Services\ServerTransfer\ServerTransferExporter::collectDependencies',
                    'App\Services\ServerTransfer\ServerTransferExporter::buildWarnings',
                    'App\Services\ServerTransfer\ServerTransferExporter::exportProject',
                    'App\Services\ServerTransfer\ServerTransferExporter::exportServer',
                ],
            ];
            $out = [];
            foreach ($features as $name => $need) {
                $out[$name] = $has($need);
            }
            $result['missing'] = $out;
            break;

        case 'crypt_check':
            // Proves that this tool and Laravel agree on the APP_KEY and format.
            $result['decrypted'] = Crypt::decryptString($input['payload']);
            $result['encrypted'] = Crypt::encryptString($input['plain']);
            break;

        case 'mark_applied':
            // Record the restored "last deployment" as matching the current
            // configuration so Coolify can reuse the restored image (no rebuild).
            $done = [];
            foreach ($input as $item) {
                $application = Application::where('uuid', $item['app_uuid'])->first();
                $deployment = ApplicationDeploymentQueue::where('deployment_uuid', $item['deployment_uuid'])->first();
                if ($application && $deployment) {
                    $application->markDeploymentConfigurationApplied($deployment);
                    $done[] = $item['app_uuid'];
                }
            }
            $result['done'] = $done;
            break;

        case 'validate_local':
            // Coolify only starts resources on a validated ("functional") server.
            $server = Server::find(0);
            if (! $server) {
                throw new RuntimeException('localhost server (id 0) not found');
            }
            $result['before'] = $server->isFunctional();
            if (! $result['before']) {
                try {
                    App\Actions\Server\ValidateServer::run($server);
                } catch (Throwable $e) {
                    $result['validation_error'] = $e->getMessage();
                }
                $server->refresh();
            }
            $result['functional'] = $server->isFunctional();
            break;

        case 'ensure_proxy':
            $server = Server::find(0);
            if (! $server) {
                throw new RuntimeException('localhost server (id 0) not found');
            }
            $result['proxy_type'] = $server->proxyType();
            $result['started'] = false;
            if (App\Actions\Proxy\CheckProxy::run($server)) {
                App\Actions\Proxy\StartProxy::run($server, async: false);
                $result['started'] = true;
            }
            break;

        case 'start':
            $out = [];
            foreach ($input as $item) {
                $row = ['type' => $item['type'], 'uuid' => $item['uuid'], 'ok' => true];
                try {
                    if ($item['type'] === 'application') {
                        $application = Application::where('uuid', $item['uuid'])->firstOrFail();
                        $deploymentUuid = new_public_id();
                        $res = queue_application_deployment(
                            application: $application,
                            deployment_uuid: $deploymentUuid,
                            commit: ($item['commit'] ?? null) ?: null,
                            force_rebuild: (bool) ($item['force_rebuild'] ?? false),
                            is_api: true,
                        );
                        $row['deployment_uuid'] = $res['deployment_uuid'] ?? $deploymentUuid;
                        $row['status'] = $res['status'] ?? null;
                        $row['message'] = $res['message'] ?? null;
                        if (($res['status'] ?? '') === 'queue_full') {
                            $row['ok'] = false;
                        }
                    } elseif ($item['type'] === 'service') {
                        $service = Service::where('uuid', $item['uuid'])->firstOrFail();
                        App\Actions\Service\StartService::run($service);
                    } else {
                        $models = cm_database_models();
                        $class = $models[$item['table']] ?? null;
                        if (! $class) {
                            throw new RuntimeException('unknown database table '.$item['table']);
                        }
                        $database = $class::where('uuid', $item['uuid'])->firstOrFail();
                        App\Actions\Database\StartDatabase::dispatch($database);
                        $database->started_at ??= now();
                        $database->save();
                    }
                } catch (Throwable $e) {
                    $row['ok'] = false;
                    $row['error'] = get_class($e).': '.$e->getMessage();
                }
                $out[] = $row;
            }
            $result['items'] = $out;
            break;

        case 'compose_files':
            // The files Coolify's own deployment writes for a Docker Compose
            // application (docker-compose.yaml with this Coolify's ids and the
            // runtime .env), generated by the same code but without cloning and
            // building, so restored images can be started as they are.
            $application = Application::where('uuid', $input['uuid'])->firstOrFail();
            if ($application->build_pack !== 'dockercompose') {
                throw new RuntimeException('not a Docker Compose application');
            }
            $commit = (string) ($input['commit'] ?? '');
            $compose = $application->parse(pull_request_id: 0, preview_id: null, commit: $commit);
            if (empty($compose)) {
                throw new RuntimeException('Coolify could not parse the compose file');
            }
            $jobClass = App\Jobs\ApplicationDeploymentJob::class;
            $job = (new ReflectionClass($jobClass))->newInstanceWithoutConstructor();
            $server = $application->destination->server;
            $env = Closure::bind(function () use ($application, $server, $commit) {
                $this->application = $application;
                $this->build_pack = $application->build_pack;
                $this->pull_request_id = 0;
                $this->commit = $commit;
                $this->branch = $application->git_branch;
                $this->server = $this->mainServer = $server;
                $this->container_name = $this->resolveContainerName();

                return $this->generate_runtime_environment_variables();
            }, $job, $jobClass)();
            $compose = convertToArray($compose);
            $result['compose'] = Symfony\Component\Yaml\Yaml::dump($compose, 10);
            $result['env'] = $env->implode("\n");
            $result['workdir'] = $application->workdir();
            $result['location'] = $application->docker_compose_location ?: '/docker-compose.yaml';
            $result['start_command'] = (string) $application->docker_compose_custom_start_command;
            $result['raw'] = (bool) $application->settings?->is_raw_compose_deployment_enabled;
            $images = [];
            foreach ((array) data_get($compose, 'services', []) as $name => $svc) {
                $images[$name] = (string) data_get($svc, 'image', '');
            }
            $result['images'] = (object) $images;
            break;

        case 'compose_started':
            // Record the direct start as a finished deployment, so Coolify's
            // history shows what happened and its later deploys compare
            // against the running configuration.
            $application = Application::where('uuid', $input['uuid'])->firstOrFail();
            $server = $application->destination->server;
            $deploymentUuid = new_public_id();
            $deployment = ApplicationDeploymentQueue::create([
                'application_id' => $application->id,
                'application_name' => $application->name,
                'server_id' => $server->id,
                'server_name' => $server->name,
                'destination_id' => $application->destination->id,
                'deployment_uuid' => $deploymentUuid,
                'deployment_url' => Spatie\Url\Url::fromString($application->link()."/deployment/{$deploymentUuid}")->getPath(),
                'pull_request_id' => 0,
                'force_rebuild' => false,
                'commit' => ($input['commit'] ?? '') ?: 'HEAD',
                'status' => ($input['ok'] ?? true) ? 'finished' : 'failed',
                'finished_at' => now(),
                'is_webhook' => false,
                'is_api' => true,
                'restart_only' => false,
            ]);
            foreach ((array) ($input['log'] ?? []) as $line) {
                $deployment->addLogEntry((string) $line);
            }
            if (method_exists($application, 'markDeploymentConfigurationApplied')) {
                $application->markDeploymentConfigurationApplied($deployment);
            }
            $result['deployment_uuid'] = $deployment->deployment_uuid;
            break;

        case 'transfer_bundle':
            // Coolify's own Server Transfer export (schema_version 1), limited to
            // the given resources of this server. The public export() refuses
            // localhost, so the same private steps are run here in the same order.
            $exporterClass = 'App\Services\ServerTransfer\ServerTransferExporter';
            if (! class_exists($exporterClass)) {
                $result['supported'] = false;
                break;
            }
            $uuids = array_flip($input['uuids'] ?? []);
            $server = Server::findOrFail(0);
            $server->loadMissing(['settings', 'privateKey', 'standaloneDockers', 'swarmDockers', 'cloudProviderToken', 'sslCertificates']);
            $pick = fn ($r) => isset($uuids[$r->uuid]);
            $applications = $server->applications()->unique('id')->filter($pick)->values();
            $databases = collect($server->databases())->unique(fn ($db) => $db::class.':'.$db->id)->filter($pick)->values();
            $services = $server->services()->get()->unique('id')->filter($pick)->values();
            $export = function () use ($server, $applications, $databases, $services) {
                $projects = App\Models\Project::query()
                    ->whereIn('id', $this->collectProjectIds($applications, $databases, $services))
                    ->orderBy('name')->get();
                $destinationUuidByKey = $this->destinationUuidMap($server);
                $dependencies = $this->collectDependencies($server, $applications, $databases, $services);
                $sourceInstanceUrl = rtrim((string) (instanceSettings()->fqdn ?: config('app.url')), '/');

                return App\Services\ServerTransfer\ServerTransferBundle::wrap([
                    'source_instance' => ['url' => $sourceInstanceUrl, 'name' => config('app.name')],
                    'warnings' => $this->buildWarnings($applications, $dependencies, $sourceInstanceUrl),
                    'private_key' => $this->exportPrivateKey($server->privateKey),
                    'private_keys' => $dependencies['private_keys']->map(fn ($k) => $this->exportPrivateKey($k))->values()->all(),
                    'github_apps' => $dependencies['github_apps']->map(fn ($a) => $this->exportGithubApp($a))->values()->all(),
                    'gitlab_apps' => $dependencies['gitlab_apps']->map(fn ($a) => $this->exportGitlabApp($a))->values()->all(),
                    's3_storages' => $dependencies['s3_storages']->map(fn ($s) => $this->exportS3Storage($s))->values()->all(),
                    'cloud_provider_tokens' => $dependencies['cloud_provider_tokens']->map(fn ($t) => $this->exportCloudProviderToken($t))->values()->all(),
                    'ssl_certificates' => $this->exportSslCertificates($server),
                    'volume_backups' => $this->exportVolumeBackups($applications, $databases, $services),
                    'server' => $this->exportServer($server),
                    'destinations' => $this->exportDestinations($server),
                    'shared_environment_variables' => ['server' => []],
                    'projects' => $projects->map(fn ($p) => $this->exportProject($p, $server, $destinationUuidByKey, $applications, $databases, $services))->values()->all(),
                ]);
            };
            $result['supported'] = true;
            $result['bundle'] = Closure::bind($export, new $exporterClass, $exporterClass)();
            break;

        case 'transfer_validate':
            // Validate a bundle with Coolify's own validator (the file is removed).
            $file = (string) ($input['file'] ?? '');
            $bundle = json_decode((string) @file_get_contents($file), true);
            @unlink($file);
            $bundleClass = 'App\Services\ServerTransfer\ServerTransferBundle';
            if (! class_exists($bundleClass)) {
                $result['supported'] = false;
                break;
            }
            if (! is_array($bundle)) {
                throw new RuntimeException('the transfer bundle is not valid JSON');
            }
            $check = $bundleClass::validate($bundle);
            $result['supported'] = true;
            $result['valid'] = $check['valid'];
            $result['errors'] = $check['errors'];
            $result['warnings'] = array_values(array_merge($check['warnings'], (array) ($bundle['warnings'] ?? [])));
            $found = [];
            foreach ((array) ($bundle['projects'] ?? []) as $project) {
                foreach ((array) ($project['environments'] ?? []) as $env) {
                    foreach (['applications', 'databases', 'services'] as $kind) {
                        foreach ((array) ($env[$kind] ?? []) as $res) {
                            $found[] = $res['uuid'] ?? '';
                        }
                    }
                }
            }
            $result['uuids'] = $found;
            break;

        case 'set_domains':
            // Same effect as editing the domain field in Coolify's UI.
            Illuminate\Support\Facades\DB::transaction(function () use ($input) {
                foreach ($input as $item) {
                    $fqdn = ($item['fqdn'] ?? '') === '' ? null : $item['fqdn'];
                    if ($fqdn !== null && class_exists(App\Support\ValidationPatterns::class) && method_exists(App\Support\ValidationPatterns::class, 'normalizeApplicationDomains')) {
                        $fqdn = App\Support\ValidationPatterns::normalizeApplicationDomains($fqdn);
                    }
                    if ($item['kind'] === 'service_app') {
                        $sa = App\Models\ServiceApplication::findOrFail($item['id']);
                        if (method_exists($sa, 'setEditableUrls')) {
                            $sa->setEditableUrls($fqdn ?? '');
                        } else {
                            $sa->fqdn = $fqdn;
                        }
                        $sa->save();
                        $sa->refresh();
                        if (function_exists('updateCompose')) {
                            updateCompose($sa);
                        }
                        $sa->service->parse();
                        continue;
                    }
                    $application = Application::where('uuid', $item['uuid'])->firstOrFail();
                    if ($item['kind'] === 'compose') {
                        $domains = json_decode($application->docker_compose_domains ?: '{}', true) ?: [];
                        $domains[$item['service']] = ['domain' => $fqdn ?? ''];
                        $application->docker_compose_domains = json_encode($domains);
                    } else {
                        $application->fqdn = $fqdn;
                    }
                    $application->save();
                    // Like the domain field in Coolify's UI: the proxy labels
                    // are generated from the domains unless they were edited by
                    // hand (otherwise the old domain keeps being routed).
                    if ($item['kind'] !== 'compose' && $application->settings?->is_container_label_readonly_enabled && function_exists('generateLabelsApplication')) {
                        $application->refresh();
                        $application->custom_labels = base64_encode(implode("\n", generateLabelsApplication($application)));
                        $application->save();
                    }
                }
            });
            break;

        default:
            throw new InvalidArgumentException("unknown action '$action'");
    }
} catch (Throwable $e) {
    $result = ['ok' => false, 'error' => get_class($e).': '.$e->getMessage()];
}

cm_out($result);
