<?php
// coolify-mirror helper. Executed inside the "coolify" container as www-data:
//   docker exec -i -u www-data -e CM_ACTION=... -e CM_INPUT=<base64 json> coolify php < runner.php
// It only calls Coolify's own actions so that containers, labels and proxy
// configuration are generated by Coolify itself.
error_reporting(E_ALL & ~E_DEPRECATED & ~E_USER_DEPRECATED);
ini_set('display_errors', 'stderr');
chdir('/var/www/html');
require '/var/www/html/vendor/autoload.php';
$app = require '/var/www/html/bootstrap/app.php';
$app->make(Illuminate\Contracts\Console\Kernel::class)->bootstrap();

use App\Models\Application;
use App\Models\ApplicationDeploymentQueue;
use App\Models\Server;
use App\Models\Service;
use Illuminate\Support\Facades\Crypt;

function cm_out(array $result): void
{
    echo "\n@@CM_RESULT@@".json_encode($result, JSON_UNESCAPED_SLASHES | JSON_PARTIAL_OUTPUT_ON_ERROR)."\n";
}

function cm_database_models(): array
{
    return [
        'standalone_postgresqls' => App\Models\StandalonePostgresql::class,
        'standalone_redis' => App\Models\StandaloneRedis::class,
        'standalone_mongodbs' => App\Models\StandaloneMongodb::class,
        'standalone_mysqls' => App\Models\StandaloneMysql::class,
        'standalone_mariadbs' => App\Models\StandaloneMariadb::class,
        'standalone_keydbs' => App\Models\StandaloneKeydb::class,
        'standalone_dragonflies' => App\Models\StandaloneDragonfly::class,
        'standalone_clickhouses' => App\Models\StandaloneClickhouse::class,
    ];
}

$action = getenv('CM_ACTION') ?: '';
$input = json_decode(base64_decode(getenv('CM_INPUT') ?: 'bnVsbA=='), true);
$result = ['ok' => true];

try {
    switch ($action) {
        case 'version':
            $result['version'] = (string) config('constants.coolify.version');
            break;

        case 'crypt_check':
            // Proves that this tool and Laravel agree on the APP_KEY and format.
            $result['decrypted'] = Crypt::decryptString($input['payload']);
            $result['encrypted'] = Crypt::encryptString($input['plain']);
            break;

        case 'mark_applied':
            // Record the restored "last deployment" as matching the current
            // configuration so Coolify can reuse the restored image (no rebuild).
            $done = [];
            foreach ($input as $item) {
                $application = Application::where('uuid', $item['app_uuid'])->first();
                $deployment = ApplicationDeploymentQueue::where('deployment_uuid', $item['deployment_uuid'])->first();
                if ($application && $deployment) {
                    $application->markDeploymentConfigurationApplied($deployment);
                    $done[] = $item['app_uuid'];
                }
            }
            $result['done'] = $done;
            break;

        case 'validate_local':
            // Coolify only starts resources on a validated ("functional") server.
            $server = Server::find(0);
            if (! $server) {
                throw new RuntimeException('localhost server (id 0) not found');
            }
            $result['before'] = $server->isFunctional();
            if (! $result['before']) {
                try {
                    App\Actions\Server\ValidateServer::run($server);
                } catch (Throwable $e) {
                    $result['validation_error'] = $e->getMessage();
                }
                $server->refresh();
            }
            $result['functional'] = $server->isFunctional();
            break;

        case 'ensure_proxy':
            $server = Server::find(0);
            if (! $server) {
                throw new RuntimeException('localhost server (id 0) not found');
            }
            $result['proxy_type'] = $server->proxyType();
            $result['started'] = false;
            if (App\Actions\Proxy\CheckProxy::run($server)) {
                App\Actions\Proxy\StartProxy::run($server, async: false);
                $result['started'] = true;
            }
            break;

        case 'start':
            $out = [];
            foreach ($input as $item) {
                $row = ['type' => $item['type'], 'uuid' => $item['uuid'], 'ok' => true];
                try {
                    if ($item['type'] === 'application') {
                        $application = Application::where('uuid', $item['uuid'])->firstOrFail();
                        $deploymentUuid = new_public_id();
                        $res = queue_application_deployment(
                            application: $application,
                            deployment_uuid: $deploymentUuid,
                            commit: ($item['commit'] ?? null) ?: null,
                            force_rebuild: false,
                            is_api: true,
                        );
                        $row['deployment_uuid'] = $res['deployment_uuid'] ?? $deploymentUuid;
                        $row['status'] = $res['status'] ?? null;
                        $row['message'] = $res['message'] ?? null;
                        if (($res['status'] ?? '') === 'queue_full') {
                            $row['ok'] = false;
                        }
                    } elseif ($item['type'] === 'service') {
                        $service = Service::where('uuid', $item['uuid'])->firstOrFail();
                        App\Actions\Service\StartService::run($service);
                    } else {
                        $models = cm_database_models();
                        $class = $models[$item['table']] ?? null;
                        if (! $class) {
                            throw new RuntimeException('unknown database table '.$item['table']);
                        }
                        $database = $class::where('uuid', $item['uuid'])->firstOrFail();
                        App\Actions\Database\StartDatabase::dispatch($database);
                        $database->started_at ??= now();
                        $database->save();
                    }
                } catch (Throwable $e) {
                    $row['ok'] = false;
                    $row['error'] = get_class($e).': '.$e->getMessage();
                }
                $out[] = $row;
            }
            $result['items'] = $out;
            break;

        case 'set_domains':
            // Same effect as editing the domain field in Coolify's UI.
            Illuminate\Support\Facades\DB::transaction(function () use ($input) {
                foreach ($input as $item) {
                    $fqdn = ($item['fqdn'] ?? '') === '' ? null : $item['fqdn'];
                    if ($fqdn !== null && class_exists(App\Support\ValidationPatterns::class) && method_exists(App\Support\ValidationPatterns::class, 'normalizeApplicationDomains')) {
                        $fqdn = App\Support\ValidationPatterns::normalizeApplicationDomains($fqdn);
                    }
                    if ($item['kind'] === 'service_app') {
                        $sa = App\Models\ServiceApplication::findOrFail($item['id']);
                        if (method_exists($sa, 'setEditableUrls')) {
                            $sa->setEditableUrls($fqdn ?? '');
                        } else {
                            $sa->fqdn = $fqdn;
                        }
                        $sa->save();
                        $sa->refresh();
                        if (function_exists('updateCompose')) {
                            updateCompose($sa);
                        }
                        $sa->service->parse();
                        continue;
                    }
                    $application = Application::where('uuid', $item['uuid'])->firstOrFail();
                    if ($item['kind'] === 'compose') {
                        $domains = json_decode($application->docker_compose_domains ?: '{}', true) ?: [];
                        $domains[$item['service']] = ['domain' => $fqdn ?? ''];
                        $application->docker_compose_domains = json_encode($domains);
                    } else {
                        $application->fqdn = $fqdn;
                    }
                    $application->save();
                }
            });
            break;

        default:
            throw new InvalidArgumentException("unknown action '$action'");
    }
} catch (Throwable $e) {
    $result = ['ok' => false, 'error' => get_class($e).': '.$e->getMessage()];
}

cm_out($result);
