package engine

import (
	"context"
	"fmt"
	"os"
	"path/filepath"
	"regexp"
	"sort"
	"strings"
	"syscall"
	"time"

	"github.com/mtalavi/coolify-mirror/internal/coolify"
	"github.com/mtalavi/coolify-mirror/internal/docker"
	"github.com/mtalavi/coolify-mirror/internal/run"
)

// Coolify builds a Docker Compose application on every deploy: it clones the
// repository and runs the build, even when the images of that commit are
// already on the server. After a restore they are (the backup carries them),
// so the application is started the way Coolify's deployment starts it after
// its build: the same docker-compose.yaml and .env, generated by Coolify for
// this server, and the same start command — without the clone and the build.
// When an image is missing or the start fails, Coolify deploys it as usual.

var composeStartTimeout = 15 * time.Minute

type composeFiles struct {
	Compose      string            `json:"compose"`
	Env          string            `json:"env"`
	Workdir      string            `json:"workdir"`
	Location     string            `json:"location"`
	StartCommand string            `json:"start_command"`
	Raw          bool              `json:"raw"`
	Images       map[string]string `json:"images"`
}

// directComposeStart starts a restored Docker Compose application from its
// images. It returns the deployment recorded in Coolify, or why it could not
// be done (the caller then lets Coolify deploy it).
func directComposeStart(ctx context.Context, in *coolify.Instance, uuid, commit string, expect []string) (deployment, reason string) {
	if commit == "" || commit == "HEAD" {
		return "", "the deployed commit is unknown"
	}
	var f composeFiles
	if err := in.PHP(ctx, "compose_files", map[string]string{"uuid": uuid, "commit": commit}, &f); err != nil {
		return "", "Coolify could not generate the compose files: " + firstLine(err.Error())
	}
	if f.Raw {
		return "", "raw compose deployment"
	}
	if !strings.HasPrefix(f.Workdir, "/data/coolify/") || strings.Contains(f.Workdir, "..") {
		return "", "unexpected configuration directory " + f.Workdir
	}
	present := func(s string) bool {
		img := f.Images[s]
		if img == "" {
			return false
		}
		_, err := run.Output(ctx, "docker", "image", "inspect", "--format", "{{.Id}}", img)
		return err == nil
	}
	var services []string
	if len(expect) == 0 {
		// Not known what ran (recovery without a backup at hand): every
		// service whose image is here.
		for s := range f.Images {
			if present(s) {
				services = append(services, s)
			}
		}
		sort.Strings(services)
	} else {
		services = composeServices(f.Images, expect)
		var missing []string
		for _, s := range services {
			if !present(s) {
				missing = append(missing, s)
			}
		}
		if len(missing) > 0 {
			return "", "no image here for " + strings.Join(missing, ", ")
		}
	}
	if len(services) == 0 {
		return "", "none of its services is in the compose file with an image here"
	}

	location := "/" + strings.TrimLeft(f.Location, "/")
	if err := writeKeepingMode(filepath.Join(f.Workdir, location), []byte(f.Compose)); err != nil {
		return "", err.Error()
	}
	if err := writeKeepingMode(filepath.Join(f.Workdir, ".env"), []byte(f.Env+"\n")); err != nil {
		return "", err.Error()
	}
	if err := docker.EnsureNetwork(ctx, uuid); err != nil {
		return "", "network " + uuid + ": " + firstLine(err.Error())
	}
	_ = docker.Connect(ctx, uuid, coolify.ProxyContainer)

	cmd := composeStartCommand(f, uuid, location, services)
	sctx, cancel := context.WithTimeout(ctx, composeStartTimeout)
	defer cancel()
	out, err := run.Do(sctx, run.Spec{Name: "sh", Args: []string{"-c", "cd " + shellQuote(f.Workdir) + " && " + cmd + " 2>&1"}})
	log := []string{
		"Started by coolify-mirror from the restored images of commit " + commit + " (no clone, no build).",
		"Services: " + strings.Join(services, ", "),
		strings.TrimSpace(tail(string(out), 4000)),
	}
	if err != nil {
		run.Logf("direct compose start of %s failed: %v", uuid, err)
		return "", "the start command failed: " + firstLine(tail(strings.TrimSpace(string(out)), 300)+" "+err.Error())
	}
	var rec struct {
		Deployment string `json:"deployment_uuid"`
	}
	if err := in.PHP(ctx, "compose_started", map[string]any{"uuid": uuid, "commit": commit, "log": log, "ok": true}, &rec); err != nil {
		run.Logf("recording the direct start of %s: %v", uuid, err)
	}
	if rec.Deployment == "" {
		rec.Deployment = "-"
	}
	return rec.Deployment, ""
}

// composeServices maps the services that ran on the source (as recorded,
// without Coolify's suffixes) to the services of the compose file.
func composeServices(images map[string]string, expect []string) []string {
	var out []string
	seen := map[string]bool{}
	for _, e := range expect {
		if _, ok := images[e]; ok && !seen[e] {
			seen[e] = true
			out = append(out, e)
		}
	}
	sort.Strings(out)
	return out
}

var (
	reComposeFile = regexp.MustCompile(`(^|\s)(-f|--file)(\s|=)`)
	reEnvFile     = regexp.MustCompile(`(^|\s)--env-file(\s|=)`)
	reUpTail      = regexp.MustCompile(`\sup((\s+-[-\w]+(=\S+)?)*)\s*$`)
)

// composeStartCommand is Coolify's start command (the custom one when set,
// with the compose and env files added the way Coolify adds them), never
// building, limited to the given services (without their dependencies) when
// the command ends with "up".
func composeStartCommand(f composeFiles, uuid, location string, services []string) string {
	file := f.Workdir + location
	env := f.Workdir + "/.env"
	var cmd string
	if c := strings.TrimSpace(f.StartCommand); c != "" {
		inject := ""
		if !reComposeFile.MatchString(c) {
			inject += " -f " + shellQuote(file)
		}
		if !reEnvFile.MatchString(c) {
			inject += " --env-file " + shellQuote(env)
		}
		cmd = strings.Replace(c, "docker compose", "docker compose"+inject, 1)
	} else {
		cmd = fmt.Sprintf("docker compose --env-file %s --project-name %s --project-directory %s -f %s up -d",
			shellQuote(env), shellQuote(uuid), shellQuote(f.Workdir), shellQuote(file))
	}
	if !reUpTail.MatchString(cmd) {
		return cmd
	}
	if !strings.Contains(cmd, "--no-build") {
		cmd += " --no-build"
	}
	// Exactly the services that ran: one-shot jobs they depend on (a
	// migration, a backup before it) already ran on the source, and their
	// images may be gone there.
	if !strings.Contains(cmd, "--no-deps") {
		cmd += " --no-deps"
	}
	for _, s := range services {
		cmd += " " + shellQuote(s)
	}
	return cmd
}

func shellQuote(s string) string {
	if regexp.MustCompile(`^[A-Za-z0-9_./=:@-]+$`).MatchString(s) {
		return s
	}
	return "'" + strings.ReplaceAll(s, "'", `'\''`) + "'"
}

func tail(s string, n int) string {
	if len(s) <= n {
		return s
	}
	return s[len(s)-n:]
}

// writeKeepingMode replaces a file, keeping the mode and owner of the
// previous one (Coolify's files belong to its own user).
func writeKeepingMode(path string, data []byte) error {
	mode := os.FileMode(0o600)
	uid, gid := -1, -1
	if st, err := os.Stat(path); err == nil {
		mode = st.Mode().Perm()
		uid, gid = fileOwner(st)
	}
	if err := os.MkdirAll(filepath.Dir(path), 0o700); err != nil {
		return err
	}
	tmp := path + ".cm-tmp"
	if err := os.WriteFile(tmp, data, mode); err != nil {
		return err
	}
	if uid >= 0 {
		_ = os.Chown(tmp, uid, gid)
	}
	return os.Rename(tmp, path)
}

func fileOwner(st os.FileInfo) (int, int) {
	if sys, ok := st.Sys().(*syscall.Stat_t); ok {
		return int(sys.Uid), int(sys.Gid)
	}
	return -1, -1
}
